# Generated by Django 2.2.1 on 2019-06-05 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video_desc', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 5, 16, 37, 49, 406454, tzinfo=utc))),
            ],
        ),
    ]
